---
title: "Homework"
---

# Unit 1 homework check (due Thursday, September 3 at 23:59:00)

-   Homework files: [Unit 1 homework instructions](homeworks/Unit 1 homework/unit.1.hw.zip)
    -   Make sure to extract (unzip) the homework files before attempting to modify them!

# Unit 1 homework (due Sunday, September 6 at 23:59:00) 

-   Homework files: [Unit 1 homework instructions](homeworks/Unit 1 homework/unit.1.hw.zip)
    -   Make sure to extract (unzip) the homework files before attempting to modify them!
  - [Unit 1 homework sample solutions]
  
# Unit 2 homework check (due Sunday, September 13 at 23:59:00)  

  - [Unit 2 homework]
  
# Unit 2 homework (due Sunday, September 20 at 23:59:00) 

  - [Unit 2 homework]
  - [Unit 2 homework sample solutions]

# Unit 3 exam (Wednesday, September 30 from 1:15 to 2:30 pm) 

  - [Unit 3 exam solutions]

# Final exam homework check (due Sunday, October 18 at 23:59:00)

  - [Final project]

# Final project (due Wednesday, October 21 at 23:59:00) 

  - [Final project]
