---
title: "Course Schedule and Class Materials"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Important: class schedule is subject to change, contingent on mitigating circumstances and the progress we make as a class. If there are any changes, I will announce them on Teams.

# Unit 1: Distributions

## Lecture 1.1: Class welcome (Monday, August 24)

Reading to do before class: Chapter 1, 2.1 and 2.2, and 3

Topics covered:

-   What are data and variables?
-   How to display quantitative and qualitative variables
-   Contingency tables

## Lecture 1.2: Characteristics of distributions (Wednesday, August 26)

Reading to do before class: Chapter 2.3-5 and 4

Topics covered:

-   How to describe the shape, center, and spread of a distribution

-   How to compare distributions

-   Dealing with problem distributions (outliers, reexpression)

-   Lecture webpage: [Lecture 1.2](lectures/lecture.1.2.html)

## Lab 1.1: R and Quarto familiarization (Wednesday, August 26)

-   Lab files: [Lab 1.1]

## Online lab 1.1 (due Sunday, August 30 at 11:59:00 pm)

-   [Introduction to R](https://learn.datacamp.com/courses/free-introduction-to-r)
-   [Introduction to the Tidyverse](https://learn.datacamp.com/courses/introduction-to-the-tidyverse)

## Lecture 1.3: Comparing distributions and the Normal distribution (Monday, August 31)

Reading to do before class: Chapter 5

Topics covered:

-   Standard deviation and standardizing values

-   Normal models

-   Normal percentiles

-   Lecture webpage: [Lecture 1.3]

## Lab 1.2: Advanced Quarto editing (Wednesday, September 2)

-   Lab files: [Lab 1.2](labs/Lab.1.2/lab.1.2.zip)

    -   Make sure to extract (unzip) the lab files before attempting to modify them!

## Unit 1 homework - progress check (due Thursday, September 3 at 23:59:00)

-   Homework files: [Unit 1 homework instructions](homeworks/Unit%201%20homework/unit.1.hw.zip)

## Online lab 1.2 (due on Friday, September 4 at 23:59:00)

-   [Introduction to Data Visualization with ggplot2](https://app.datacamp.com/learn/courses/introduction-to-data-visualization-with-ggplot2)

## Unit 1 homework (due Sunday, September 6 23:59:00 pm)

-   Homework files: [Unit 1 homework instructions](homeworks/Unit%201%20homework/unit.1.hw.zip)
-   Homework sample solutions: Unit 1 homework sample solutions

# Unit 2: Relationships between variables

## Lecture 2.1: Association and correlation (Wednesday, September 2)

Reading to do before class: Chapter 6

Podcast for class: 

Topics covered:

-   Scatterplots

-   Correlations

-   Does correlation imply causation?

-   Lecture webpage: [Lecture 2.1]

## Lecture 2.2: Simple Linear Regression (Monday, September 7)

Reading to do before class: Chapter 7

Topics covered:

-   Line of best fit: least squares

-   The linear model

-   What are residuals

-   Regression assumptions

-   Lecture webpage: [Lecture 2.2]

## Lecture 2.3: Regression Wisdom (Wednesday, September 9)

Podcast for class: 

Reading to do before class: Chapter 8

Topics covered:

-   Beware extrapolation

-   Outliers and leverage

-   Lurking variables

-   Straightening scatterplots

-   Lecture webpage: [Lecture 2.3]

## Lab 2.1: Working with regressions using `dplyr` (Wednesday, September 9)

-   Lab files: [Lab 2.1](labs/Lab.2.1/lab.2.1.zip)

    -   Make sure to extract (unzip) the lab files before attempting to modify them!

## Online lab 2.2 (due on Friday, September 11 at 23:59:00)

-   [Intermediate Data Visualization with ggplot2](https://app.datacamp.com/learn/courses/intermediate-data-visualization-with-ggplot2)

## Unit 2 homework - progress check (due Sunday, September 13 at 23:59:00)

-   Homework files: [Unit 2 homework instructions]

## Lecture 2.4: Multiple Regression (Monday, September 14)

Reading to do before class: Chapter 9

Topics covered:

-   What is multiple regression?

-   Interpreting multiple regression coefficients

-   Partial regression plots

-   Indicator variables

-   Lecture webpage: [Lecture 2.4]

## Unit 2 homework (due Sunday, September 20 at 11:59:00)

-   Homework files: [Unit 2 homework instructions]

# Unit 3: Measuring uncertainty

## Lecture 3.1: Confidence intervals - proportions (Wednesday, September 16)

Podcast for class: 

Reading to do before class: Chapter 13

Topics covered:

-   What is a sampling distribution?

-   When does the normal model apply?

-   Constructing a confidence interval

-   Interpreting a confidence interval

-   Lecture webpage: [Lecture 3.1]

## Lab 2.2: Interpreting coefficients (Wednesday, September 16)

-   Lab files: [Lab 2.2]

## Lecture 3.2: Confidence intervals - means (Monday, September 21)

Reading to do before class: Chapter 14

Topics covered:

-   The Central Limit Theorem

-   Confidence interval for means

-   Interpreting a confidence interval

-   Final thoughts on confidence intervals

-   Lecture webpage: [Lecture 3.2]

## Lecture 3.3: Hypothesis testing (Wednesday, September 23)

Reading to do before class: Chapter 15

Topics covered:

-   What are hypotheses?

-   $p$ values

-   $p$ values and decisions -- how to make a decision

-   Lecture webpage: [Lecture 3.3]

## Lab 3.1: Bootstrapping (Wednesday, September 23)

-   Lab files: [Lab 3.1]

    -   Make sure to extract (unzip) the lab files before attempting to modify them!

## Lecture 3.4: Hypothesis testing wisdom (Monday, September 28)

Reading to do before class: Chapter 16

Topics covered:

-   Interpreting p-values

-   Alpha and critical values

-   Practical vs. statistical significance

-   Type I and II errors

-   Power of a test

-   Lecture webpage: [Lecture 3.4]

# Unit 4: Statistical inference

## Lecture 4.1: Comparing groups (Wednesday, September 30)

Reading to do before class: Chapter 17

Topics covered:

-   Confidence intervals for comparing two samples

-   Assumptions and conditions for two-sample hypothesis tests

-   Two-sample $z$ test

-   Two-sample $t$ test

-   Lecture webpage: [Lecture 4.1](lectures/lecture.4.1.html)

## In-class Unit 3 exam: Wednesday, September 30 from 1:15 pm to 2:30 pm

## Lecture 4.2: Returning to regression (Monday, October 12)

Reading to do before class: Chapter 20

Topics covered:

-   Regression inference and intuition

-   The regression table

-   Confidence and prediction intervals

-   Lecture webpage: [Lecture 4.2](lectures/lecture.4.2.html)

## Lab 4.1: Interpretation activity (Wednesday, October 14)

-   [Reading]
-   [Activity]

## Online lab 4.1 (due on Friday, October 16 at 11:59:00)

-   Your choice of any DataCamp course (as long as it relates to statistics)

    -   Send the completion certificate from the end of the course to the lab manager, Jingyu Wang, on Teams

## Final project - progress check (due Sunday, October 18 at 23:59:00)

-   Homework files: [Final project instructions]

## Final project (due Wednesday, October 21 at 23:59:00)

-   Homework files: [Final project instructions]